//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.SOAReservasService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SOAReservasService.IReservasService")]
    public interface IReservasService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservasService/ListarEspacioComun", ReplyAction="http://tempuri.org/IReservasService/ListarEspacioComunResponse")]
        Architects.Dominio.EspacioComun[] ListarEspacioComun();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReservasServiceChannel : Test.SOAReservasService.IReservasService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReservasServiceClient : System.ServiceModel.ClientBase<Test.SOAReservasService.IReservasService>, Test.SOAReservasService.IReservasService {
        
        public ReservasServiceClient() {
        }
        
        public ReservasServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReservasServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservasServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservasServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Architects.Dominio.EspacioComun[] ListarEspacioComun() {
            return base.Channel.ListarEspacioComun();
        }
    }
}
