//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Architecs.Presentacion.PagosService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoPago", Namespace="http://schemas.datacontract.org/2004/07/Architecs.PagosService")]
    [System.SerializableAttribute()]
    public partial class TipoPago : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool B_EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C_DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int N_IdTipoPagoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool B_Estado {
            get {
                return this.B_EstadoField;
            }
            set {
                if ((this.B_EstadoField.Equals(value) != true)) {
                    this.B_EstadoField = value;
                    this.RaisePropertyChanged("B_Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string C_Descripcion {
            get {
                return this.C_DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.C_DescripcionField, value) != true)) {
                    this.C_DescripcionField = value;
                    this.RaisePropertyChanged("C_Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int N_IdTipoPago {
            get {
                return this.N_IdTipoPagoField;
            }
            set {
                if ((this.N_IdTipoPagoField.Equals(value) != true)) {
                    this.N_IdTipoPagoField = value;
                    this.RaisePropertyChanged("N_IdTipoPago");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cuota", Namespace="http://schemas.datacontract.org/2004/07/Architecs.PagosService")]
    [System.SerializableAttribute()]
    public partial class Cuota : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C_NumDepositoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C_PeriodoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> D_FecPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> D_FecVnctoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int N_IdCuotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> N_IdTipoPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int N_IdViviendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> N_ImporteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Architecs.Presentacion.PagosService.TipoPago objTipoPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Architects.Dominio.ViviendaBE objViviendaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string C_NumDeposito {
            get {
                return this.C_NumDepositoField;
            }
            set {
                if ((object.ReferenceEquals(this.C_NumDepositoField, value) != true)) {
                    this.C_NumDepositoField = value;
                    this.RaisePropertyChanged("C_NumDeposito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string C_Periodo {
            get {
                return this.C_PeriodoField;
            }
            set {
                if ((object.ReferenceEquals(this.C_PeriodoField, value) != true)) {
                    this.C_PeriodoField = value;
                    this.RaisePropertyChanged("C_Periodo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> D_FecPago {
            get {
                return this.D_FecPagoField;
            }
            set {
                if ((this.D_FecPagoField.Equals(value) != true)) {
                    this.D_FecPagoField = value;
                    this.RaisePropertyChanged("D_FecPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> D_FecVncto {
            get {
                return this.D_FecVnctoField;
            }
            set {
                if ((this.D_FecVnctoField.Equals(value) != true)) {
                    this.D_FecVnctoField = value;
                    this.RaisePropertyChanged("D_FecVncto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int N_IdCuota {
            get {
                return this.N_IdCuotaField;
            }
            set {
                if ((this.N_IdCuotaField.Equals(value) != true)) {
                    this.N_IdCuotaField = value;
                    this.RaisePropertyChanged("N_IdCuota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> N_IdTipoPago {
            get {
                return this.N_IdTipoPagoField;
            }
            set {
                if ((this.N_IdTipoPagoField.Equals(value) != true)) {
                    this.N_IdTipoPagoField = value;
                    this.RaisePropertyChanged("N_IdTipoPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int N_IdVivienda {
            get {
                return this.N_IdViviendaField;
            }
            set {
                if ((this.N_IdViviendaField.Equals(value) != true)) {
                    this.N_IdViviendaField = value;
                    this.RaisePropertyChanged("N_IdVivienda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> N_Importe {
            get {
                return this.N_ImporteField;
            }
            set {
                if ((this.N_ImporteField.Equals(value) != true)) {
                    this.N_ImporteField = value;
                    this.RaisePropertyChanged("N_Importe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Architecs.Presentacion.PagosService.TipoPago objTipoPago {
            get {
                return this.objTipoPagoField;
            }
            set {
                if ((object.ReferenceEquals(this.objTipoPagoField, value) != true)) {
                    this.objTipoPagoField = value;
                    this.RaisePropertyChanged("objTipoPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Architects.Dominio.ViviendaBE objVivienda {
            get {
                return this.objViviendaField;
            }
            set {
                if ((object.ReferenceEquals(this.objViviendaField, value) != true)) {
                    this.objViviendaField = value;
                    this.RaisePropertyChanged("objVivienda");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PagosService.IPagosService")]
    public interface IPagosService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagosService/ListarTipoPago", ReplyAction="http://tempuri.org/IPagosService/ListarTipoPagoResponse")]
        Architecs.Presentacion.PagosService.TipoPago[] ListarTipoPago();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagosService/RegistrarTipoPago", ReplyAction="http://tempuri.org/IPagosService/RegistrarTipoPagoResponse")]
        Architects.Dominio.RetornaMensaje RegistrarTipoPago(string Descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagosService/RegistrarCuota", ReplyAction="http://tempuri.org/IPagosService/RegistrarCuotaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Architects.Dominio.RetornaMensaje), Action="http://tempuri.org/IPagosService/RegistrarCuotaRetornaMensajeFault", Name="RetornaMensaje", Namespace="http://schemas.datacontract.org/2004/07/Architects.Dominio")]
        Architects.Dominio.RetornaMensaje RegistrarCuota(string pPeriodo, int pIdVivienda, double pImporte, string pFecVncto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagosService/ActualizarCuota", ReplyAction="http://tempuri.org/IPagosService/ActualizarCuotaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Architects.Dominio.RetornaMensaje), Action="http://tempuri.org/IPagosService/ActualizarCuotaRetornaMensajeFault", Name="RetornaMensaje", Namespace="http://schemas.datacontract.org/2004/07/Architects.Dominio")]
        Architects.Dominio.RetornaMensaje ActualizarCuota(int pIdCuota, string pPeriodo, int pIdVivienda, double pImporte, string pFecVncto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagosService/PagarCuota", ReplyAction="http://tempuri.org/IPagosService/PagarCuotaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Architects.Dominio.RetornaMensaje), Action="http://tempuri.org/IPagosService/PagarCuotaRetornaMensajeFault", Name="RetornaMensaje", Namespace="http://schemas.datacontract.org/2004/07/Architects.Dominio")]
        Architects.Dominio.RetornaMensaje PagarCuota(int pIdCuota, string pFecPago, string pNumDeposito, int pTipoPago);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagosService/ListarCuota", ReplyAction="http://tempuri.org/IPagosService/ListarCuotaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Architects.Dominio.RetornaMensaje), Action="http://tempuri.org/IPagosService/ListarCuotaRetornaMensajeFault", Name="RetornaMensaje", Namespace="http://schemas.datacontract.org/2004/07/Architects.Dominio")]
        Architecs.Presentacion.PagosService.Cuota[] ListarCuota(string pPeriodo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagosService/ListarCuotaPorResidente", ReplyAction="http://tempuri.org/IPagosService/ListarCuotaPorResidenteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Architects.Dominio.RetornaMensaje), Action="http://tempuri.org/IPagosService/ListarCuotaPorResidenteRetornaMensajeFault", Name="RetornaMensaje", Namespace="http://schemas.datacontract.org/2004/07/Architects.Dominio")]
        Architecs.Presentacion.PagosService.Cuota[] ListarCuotaPorResidente(string pCorreoResidente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagosService/ListarCuotaMorosas", ReplyAction="http://tempuri.org/IPagosService/ListarCuotaMorosasResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Architects.Dominio.RetornaMensaje), Action="http://tempuri.org/IPagosService/ListarCuotaMorosasRetornaMensajeFault", Name="RetornaMensaje", Namespace="http://schemas.datacontract.org/2004/07/Architects.Dominio")]
        Architecs.Presentacion.PagosService.Cuota[] ListarCuotaMorosas(string pPeriodo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagosService/BuscarCuota", ReplyAction="http://tempuri.org/IPagosService/BuscarCuotaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Architects.Dominio.RetornaMensaje), Action="http://tempuri.org/IPagosService/BuscarCuotaRetornaMensajeFault", Name="RetornaMensaje", Namespace="http://schemas.datacontract.org/2004/07/Architects.Dominio")]
        Architecs.Presentacion.PagosService.Cuota BuscarCuota(int pIdCuota);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagosService/EliminarCuota", ReplyAction="http://tempuri.org/IPagosService/EliminarCuotaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Architects.Dominio.RetornaMensaje), Action="http://tempuri.org/IPagosService/EliminarCuotaRetornaMensajeFault", Name="RetornaMensaje", Namespace="http://schemas.datacontract.org/2004/07/Architects.Dominio")]
        Architects.Dominio.RetornaMensaje EliminarCuota(int pIdCuota);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPagosServiceChannel : Architecs.Presentacion.PagosService.IPagosService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PagosServiceClient : System.ServiceModel.ClientBase<Architecs.Presentacion.PagosService.IPagosService>, Architecs.Presentacion.PagosService.IPagosService {
        
        public PagosServiceClient() {
        }
        
        public PagosServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PagosServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PagosServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PagosServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Architecs.Presentacion.PagosService.TipoPago[] ListarTipoPago() {
            return base.Channel.ListarTipoPago();
        }
        
        public Architects.Dominio.RetornaMensaje RegistrarTipoPago(string Descripcion) {
            return base.Channel.RegistrarTipoPago(Descripcion);
        }
        
        public Architects.Dominio.RetornaMensaje RegistrarCuota(string pPeriodo, int pIdVivienda, double pImporte, string pFecVncto) {
            return base.Channel.RegistrarCuota(pPeriodo, pIdVivienda, pImporte, pFecVncto);
        }
        
        public Architects.Dominio.RetornaMensaje ActualizarCuota(int pIdCuota, string pPeriodo, int pIdVivienda, double pImporte, string pFecVncto) {
            return base.Channel.ActualizarCuota(pIdCuota, pPeriodo, pIdVivienda, pImporte, pFecVncto);
        }
        
        public Architects.Dominio.RetornaMensaje PagarCuota(int pIdCuota, string pFecPago, string pNumDeposito, int pTipoPago) {
            return base.Channel.PagarCuota(pIdCuota, pFecPago, pNumDeposito, pTipoPago);
        }
        
        public Architecs.Presentacion.PagosService.Cuota[] ListarCuota(string pPeriodo) {
            return base.Channel.ListarCuota(pPeriodo);
        }
        
        public Architecs.Presentacion.PagosService.Cuota[] ListarCuotaPorResidente(string pCorreoResidente) {
            return base.Channel.ListarCuotaPorResidente(pCorreoResidente);
        }
        
        public Architecs.Presentacion.PagosService.Cuota[] ListarCuotaMorosas(string pPeriodo) {
            return base.Channel.ListarCuotaMorosas(pPeriodo);
        }
        
        public Architecs.Presentacion.PagosService.Cuota BuscarCuota(int pIdCuota) {
            return base.Channel.BuscarCuota(pIdCuota);
        }
        
        public Architects.Dominio.RetornaMensaje EliminarCuota(int pIdCuota) {
            return base.Channel.EliminarCuota(pIdCuota);
        }
    }
}
