#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Architecs.EspaciosComunuesService.Persistencia
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CondominiosDB")]
	public partial class DBMLEspacioComunDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DBMLEspacioComunDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["CondominiosDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBMLEspacioComunDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBMLEspacioComunDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBMLEspacioComunDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBMLEspacioComunDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Maestros.dsd_mnt_D_EspacioComun")]
		public int dsd_mnt_D_EspacioComun([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_N_IdEspacioComun)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), prm_N_IdEspacioComun);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Maestros.dsd_mnt_I_EspacioComun")]
		public ISingleResult<dsd_mnt_I_EspacioComunResult> dsd_mnt_I_EspacioComun([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string prm_C_Nombre)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), prm_C_Nombre);
			return ((ISingleResult<dsd_mnt_I_EspacioComunResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Maestros.dsd_mnt_S_EspacioComun")]
		public ISingleResult<dsd_mnt_S_EspacioComunResult> dsd_mnt_S_EspacioComun()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<dsd_mnt_S_EspacioComunResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Maestros.dsd_mnt_U_EspacioComun")]
		public int dsd_mnt_U_EspacioComun([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_N_IdEspacioComun, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string prm_C_Nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_B_Estado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), prm_N_IdEspacioComun, prm_C_Nombre, prm_B_Estado);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class dsd_mnt_I_EspacioComunResult
	{
		
		private System.Nullable<decimal> _Column1;
		
		public dsd_mnt_I_EspacioComunResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
	
	public partial class dsd_mnt_S_EspacioComunResult
	{
		
		private int _N_IdEspacioComun;
		
		private string _C_Nombre;
		
		private int _B_Estado;
		
		public dsd_mnt_S_EspacioComunResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N_IdEspacioComun", DbType="Int NOT NULL")]
		public int N_IdEspacioComun
		{
			get
			{
				return this._N_IdEspacioComun;
			}
			set
			{
				if ((this._N_IdEspacioComun != value))
				{
					this._N_IdEspacioComun = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Nombre", DbType="VarChar(100)")]
		public string C_Nombre
		{
			get
			{
				return this._C_Nombre;
			}
			set
			{
				if ((this._C_Nombre != value))
				{
					this._C_Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B_Estado", DbType="Int NOT NULL")]
		public int B_Estado
		{
			get
			{
				return this._B_Estado;
			}
			set
			{
				if ((this._B_Estado != value))
				{
					this._B_Estado = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
