//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Architects.TestProject.SOAPagosService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoPago", Namespace="http://schemas.datacontract.org/2004/07/Architecs.PagosService")]
    [System.SerializableAttribute()]
    public partial class TipoPago : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool B_EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C_DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int N_IdTipoPagoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool B_Estado {
            get {
                return this.B_EstadoField;
            }
            set {
                if ((this.B_EstadoField.Equals(value) != true)) {
                    this.B_EstadoField = value;
                    this.RaisePropertyChanged("B_Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string C_Descripcion {
            get {
                return this.C_DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.C_DescripcionField, value) != true)) {
                    this.C_DescripcionField = value;
                    this.RaisePropertyChanged("C_Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int N_IdTipoPago {
            get {
                return this.N_IdTipoPagoField;
            }
            set {
                if ((this.N_IdTipoPagoField.Equals(value) != true)) {
                    this.N_IdTipoPagoField = value;
                    this.RaisePropertyChanged("N_IdTipoPago");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetornaMensaje", Namespace="http://schemas.datacontract.org/2004/07/Architecs.Dominio")]
    [System.SerializableAttribute()]
    public partial class RetornaMensaje : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoRetornoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ExitoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoError {
            get {
                return this.CodigoErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoErrorField, value) != true)) {
                    this.CodigoErrorField = value;
                    this.RaisePropertyChanged("CodigoError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoRetorno {
            get {
                return this.CodigoRetornoField;
            }
            set {
                if ((this.CodigoRetornoField.Equals(value) != true)) {
                    this.CodigoRetornoField = value;
                    this.RaisePropertyChanged("CodigoRetorno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Exito {
            get {
                return this.ExitoField;
            }
            set {
                if ((this.ExitoField.Equals(value) != true)) {
                    this.ExitoField = value;
                    this.RaisePropertyChanged("Exito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensage {
            get {
                return this.MensageField;
            }
            set {
                if ((object.ReferenceEquals(this.MensageField, value) != true)) {
                    this.MensageField = value;
                    this.RaisePropertyChanged("Mensage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cuota", Namespace="http://schemas.datacontract.org/2004/07/Architecs.PagosService")]
    [System.SerializableAttribute()]
    public partial class Cuota : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C_PeriodoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> D_FecPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> D_FecVnctoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int N_IdCuotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int N_IdTipoPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int N_IdViviendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> N_ImporteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Architects.TestProject.SOAPagosService.TipoPago objTipoPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Architects.TestProject.SOAPagosService.Vivienda objViviendaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string C_Periodo {
            get {
                return this.C_PeriodoField;
            }
            set {
                if ((object.ReferenceEquals(this.C_PeriodoField, value) != true)) {
                    this.C_PeriodoField = value;
                    this.RaisePropertyChanged("C_Periodo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> D_FecPago {
            get {
                return this.D_FecPagoField;
            }
            set {
                if ((this.D_FecPagoField.Equals(value) != true)) {
                    this.D_FecPagoField = value;
                    this.RaisePropertyChanged("D_FecPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> D_FecVncto {
            get {
                return this.D_FecVnctoField;
            }
            set {
                if ((this.D_FecVnctoField.Equals(value) != true)) {
                    this.D_FecVnctoField = value;
                    this.RaisePropertyChanged("D_FecVncto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int N_IdCuota {
            get {
                return this.N_IdCuotaField;
            }
            set {
                if ((this.N_IdCuotaField.Equals(value) != true)) {
                    this.N_IdCuotaField = value;
                    this.RaisePropertyChanged("N_IdCuota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int N_IdTipoPago {
            get {
                return this.N_IdTipoPagoField;
            }
            set {
                if ((this.N_IdTipoPagoField.Equals(value) != true)) {
                    this.N_IdTipoPagoField = value;
                    this.RaisePropertyChanged("N_IdTipoPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int N_IdVivienda {
            get {
                return this.N_IdViviendaField;
            }
            set {
                if ((this.N_IdViviendaField.Equals(value) != true)) {
                    this.N_IdViviendaField = value;
                    this.RaisePropertyChanged("N_IdVivienda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> N_Importe {
            get {
                return this.N_ImporteField;
            }
            set {
                if ((this.N_ImporteField.Equals(value) != true)) {
                    this.N_ImporteField = value;
                    this.RaisePropertyChanged("N_Importe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Architects.TestProject.SOAPagosService.TipoPago objTipoPago {
            get {
                return this.objTipoPagoField;
            }
            set {
                if ((object.ReferenceEquals(this.objTipoPagoField, value) != true)) {
                    this.objTipoPagoField = value;
                    this.RaisePropertyChanged("objTipoPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Architects.TestProject.SOAPagosService.Vivienda objVivienda {
            get {
                return this.objViviendaField;
            }
            set {
                if ((object.ReferenceEquals(this.objViviendaField, value) != true)) {
                    this.objViviendaField = value;
                    this.RaisePropertyChanged("objVivienda");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vivienda", Namespace="http://schemas.datacontract.org/2004/07/Architecs.Dominio")]
    [System.SerializableAttribute()]
    public partial class Vivienda : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool B_EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C_CodTipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C_NumDptoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C_NumEdificioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int N_IdResidenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int N_IdViviendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal N_NumMetrosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Architects.TestProject.SOAPagosService.Residente objResidenteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool B_Estado {
            get {
                return this.B_EstadoField;
            }
            set {
                if ((this.B_EstadoField.Equals(value) != true)) {
                    this.B_EstadoField = value;
                    this.RaisePropertyChanged("B_Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string C_CodTipo {
            get {
                return this.C_CodTipoField;
            }
            set {
                if ((object.ReferenceEquals(this.C_CodTipoField, value) != true)) {
                    this.C_CodTipoField = value;
                    this.RaisePropertyChanged("C_CodTipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string C_NumDpto {
            get {
                return this.C_NumDptoField;
            }
            set {
                if ((object.ReferenceEquals(this.C_NumDptoField, value) != true)) {
                    this.C_NumDptoField = value;
                    this.RaisePropertyChanged("C_NumDpto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string C_NumEdificio {
            get {
                return this.C_NumEdificioField;
            }
            set {
                if ((object.ReferenceEquals(this.C_NumEdificioField, value) != true)) {
                    this.C_NumEdificioField = value;
                    this.RaisePropertyChanged("C_NumEdificio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int N_IdResidente {
            get {
                return this.N_IdResidenteField;
            }
            set {
                if ((this.N_IdResidenteField.Equals(value) != true)) {
                    this.N_IdResidenteField = value;
                    this.RaisePropertyChanged("N_IdResidente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int N_IdVivienda {
            get {
                return this.N_IdViviendaField;
            }
            set {
                if ((this.N_IdViviendaField.Equals(value) != true)) {
                    this.N_IdViviendaField = value;
                    this.RaisePropertyChanged("N_IdVivienda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal N_NumMetros {
            get {
                return this.N_NumMetrosField;
            }
            set {
                if ((this.N_NumMetrosField.Equals(value) != true)) {
                    this.N_NumMetrosField = value;
                    this.RaisePropertyChanged("N_NumMetros");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Architects.TestProject.SOAPagosService.Residente objResidente {
            get {
                return this.objResidenteField;
            }
            set {
                if ((object.ReferenceEquals(this.objResidenteField, value) != true)) {
                    this.objResidenteField = value;
                    this.RaisePropertyChanged("objResidente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Residente", Namespace="http://schemas.datacontract.org/2004/07/Architecs.Dominio")]
    [System.SerializableAttribute()]
    public partial class Residente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool B_EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C_ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C_ClaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C_CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C_NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C_NumDocumeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime D_FecNacimiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int N_IdResidenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int N_TipoDocField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool B_Estado {
            get {
                return this.B_EstadoField;
            }
            set {
                if ((this.B_EstadoField.Equals(value) != true)) {
                    this.B_EstadoField = value;
                    this.RaisePropertyChanged("B_Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string C_Apellidos {
            get {
                return this.C_ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.C_ApellidosField, value) != true)) {
                    this.C_ApellidosField = value;
                    this.RaisePropertyChanged("C_Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string C_Clave {
            get {
                return this.C_ClaveField;
            }
            set {
                if ((object.ReferenceEquals(this.C_ClaveField, value) != true)) {
                    this.C_ClaveField = value;
                    this.RaisePropertyChanged("C_Clave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string C_Correo {
            get {
                return this.C_CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.C_CorreoField, value) != true)) {
                    this.C_CorreoField = value;
                    this.RaisePropertyChanged("C_Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string C_Nombre {
            get {
                return this.C_NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.C_NombreField, value) != true)) {
                    this.C_NombreField = value;
                    this.RaisePropertyChanged("C_Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string C_NumDocume {
            get {
                return this.C_NumDocumeField;
            }
            set {
                if ((object.ReferenceEquals(this.C_NumDocumeField, value) != true)) {
                    this.C_NumDocumeField = value;
                    this.RaisePropertyChanged("C_NumDocume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime D_FecNacimi {
            get {
                return this.D_FecNacimiField;
            }
            set {
                if ((this.D_FecNacimiField.Equals(value) != true)) {
                    this.D_FecNacimiField = value;
                    this.RaisePropertyChanged("D_FecNacimi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int N_IdResidente {
            get {
                return this.N_IdResidenteField;
            }
            set {
                if ((this.N_IdResidenteField.Equals(value) != true)) {
                    this.N_IdResidenteField = value;
                    this.RaisePropertyChanged("N_IdResidente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int N_TipoDoc {
            get {
                return this.N_TipoDocField;
            }
            set {
                if ((this.N_TipoDocField.Equals(value) != true)) {
                    this.N_TipoDocField = value;
                    this.RaisePropertyChanged("N_TipoDoc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SOAPagosService.IPagosService")]
    public interface IPagosService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagosService/ListarTipoPago", ReplyAction="http://tempuri.org/IPagosService/ListarTipoPagoResponse")]
        Architects.TestProject.SOAPagosService.TipoPago[] ListarTipoPago();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagosService/RegistrarTipoPago", ReplyAction="http://tempuri.org/IPagosService/RegistrarTipoPagoResponse")]
        Architects.TestProject.SOAPagosService.RetornaMensaje RegistrarTipoPago(string Descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagosService/RegistrarCuota", ReplyAction="http://tempuri.org/IPagosService/RegistrarCuotaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Architects.TestProject.SOAPagosService.RetornaMensaje), Action="http://tempuri.org/IPagosService/RegistrarCuotaRetornaMensajeFault", Name="RetornaMensaje", Namespace="http://schemas.datacontract.org/2004/07/Architecs.Dominio")]
        Architects.TestProject.SOAPagosService.RetornaMensaje RegistrarCuota(string pPeriodo, int pIdVivienda, int pIdTipoPago, decimal pImporte, System.DateTime pFecVncto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagosService/ActualizarCuota", ReplyAction="http://tempuri.org/IPagosService/ActualizarCuotaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Architects.TestProject.SOAPagosService.RetornaMensaje), Action="http://tempuri.org/IPagosService/ActualizarCuotaRetornaMensajeFault", Name="RetornaMensaje", Namespace="http://schemas.datacontract.org/2004/07/Architecs.Dominio")]
        Architects.TestProject.SOAPagosService.RetornaMensaje ActualizarCuota(int pIdCuota, string pPeriodo, int pIdVivienda, int pIdTipoPago, decimal pImporte, System.DateTime pFecVncto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagosService/ListarCuota", ReplyAction="http://tempuri.org/IPagosService/ListarCuotaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Architects.TestProject.SOAPagosService.RetornaMensaje), Action="http://tempuri.org/IPagosService/ListarCuotaRetornaMensajeFault", Name="RetornaMensaje", Namespace="http://schemas.datacontract.org/2004/07/Architecs.Dominio")]
        Architects.TestProject.SOAPagosService.Cuota[] ListarCuota(string pPeriodo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagosService/BuscarCuota", ReplyAction="http://tempuri.org/IPagosService/BuscarCuotaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Architects.TestProject.SOAPagosService.RetornaMensaje), Action="http://tempuri.org/IPagosService/BuscarCuotaRetornaMensajeFault", Name="RetornaMensaje", Namespace="http://schemas.datacontract.org/2004/07/Architecs.Dominio")]
        Architects.TestProject.SOAPagosService.Cuota BuscarCuota(int pIdCuota);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagosService/EliminarCuota", ReplyAction="http://tempuri.org/IPagosService/EliminarCuotaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Architects.TestProject.SOAPagosService.RetornaMensaje), Action="http://tempuri.org/IPagosService/EliminarCuotaRetornaMensajeFault", Name="RetornaMensaje", Namespace="http://schemas.datacontract.org/2004/07/Architecs.Dominio")]
        Architects.TestProject.SOAPagosService.RetornaMensaje EliminarCuota(int pIdCuota);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPagosServiceChannel : Architects.TestProject.SOAPagosService.IPagosService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PagosServiceClient : System.ServiceModel.ClientBase<Architects.TestProject.SOAPagosService.IPagosService>, Architects.TestProject.SOAPagosService.IPagosService {
        
        public PagosServiceClient() {
        }
        
        public PagosServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PagosServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PagosServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PagosServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Architects.TestProject.SOAPagosService.TipoPago[] ListarTipoPago() {
            return base.Channel.ListarTipoPago();
        }
        
        public Architects.TestProject.SOAPagosService.RetornaMensaje RegistrarTipoPago(string Descripcion) {
            return base.Channel.RegistrarTipoPago(Descripcion);
        }
        
        public Architects.TestProject.SOAPagosService.RetornaMensaje RegistrarCuota(string pPeriodo, int pIdVivienda, int pIdTipoPago, decimal pImporte, System.DateTime pFecVncto) {
            return base.Channel.RegistrarCuota(pPeriodo, pIdVivienda, pIdTipoPago, pImporte, pFecVncto);
        }
        
        public Architects.TestProject.SOAPagosService.RetornaMensaje ActualizarCuota(int pIdCuota, string pPeriodo, int pIdVivienda, int pIdTipoPago, decimal pImporte, System.DateTime pFecVncto) {
            return base.Channel.ActualizarCuota(pIdCuota, pPeriodo, pIdVivienda, pIdTipoPago, pImporte, pFecVncto);
        }
        
        public Architects.TestProject.SOAPagosService.Cuota[] ListarCuota(string pPeriodo) {
            return base.Channel.ListarCuota(pPeriodo);
        }
        
        public Architects.TestProject.SOAPagosService.Cuota BuscarCuota(int pIdCuota) {
            return base.Channel.BuscarCuota(pIdCuota);
        }
        
        public Architects.TestProject.SOAPagosService.RetornaMensaje EliminarCuota(int pIdCuota) {
            return base.Channel.EliminarCuota(pIdCuota);
        }
    }
}
