<?xml version="1.0" encoding="utf-8"?><Database Name="CondominiosDB" Class="DBMLPagosDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=CondominiosDB.mssql.somee.com;Initial Catalog=CondominiosDB;User ID=julioanyosa_SQLLogin_1" SettingsObjectName="Architects.Persistencia.Properties.Settings" SettingsPropertyName="CondominiosDBConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="Maestros.dsd_mnt_S_TipoPago" Method="dsd_mnt_S_TipoPago">
    <ElementType Name="dsd_mnt_S_TipoPagoResult">
      <Column Name="N_IdTipoPago" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="C_Descripcion" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Column Name="B_Estado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="Maestros.dsd_mnt_I_TipoPago" Method="dsd_mnt_I_TipoPago">
    <Parameter Name="prmN_IdTipoPago" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="prm_C_Descripcion" Type="System.String" DbType="VarChar(45)" />
    <Parameter Name="prm_B_Estado" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Maestros.dsd_mnt_S_TipoPagoId" Method="dsd_mnt_S_TipoPagoId">
    <Parameter Name="prm_N_IdTipoPago" Type="System.Int32" DbType="Int" />
    <ElementType Name="dsd_mnt_S_TipoPagoIdResult">
      <Column Name="N_IdTipoPago" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="C_Descripcion" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Column Name="B_Estado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>