#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Architects.Persistencia
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CondominiosDB")]
	public partial class DBMLPagosDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DBMLPagosDataContext() : 
				base(global::Architects.Persistencia.Properties.Settings.Default.CondominiosDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBMLPagosDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBMLPagosDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBMLPagosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBMLPagosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Maestros.dsd_mnt_S_TipoPago")]
		public ISingleResult<dsd_mnt_S_TipoPagoResult> dsd_mnt_S_TipoPago()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<dsd_mnt_S_TipoPagoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Maestros.dsd_mnt_I_TipoPago")]
		public int dsd_mnt_I_TipoPago([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> prmN_IdTipoPago, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(45)")] string prm_C_Descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> prm_B_Estado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), prmN_IdTipoPago, prm_C_Descripcion, prm_B_Estado);
			prmN_IdTipoPago = ((System.Nullable<int>)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Maestros.dsd_mnt_S_TipoPagoId")]
		public ISingleResult<dsd_mnt_S_TipoPagoIdResult> dsd_mnt_S_TipoPagoId([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_N_IdTipoPago)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), prm_N_IdTipoPago);
			return ((ISingleResult<dsd_mnt_S_TipoPagoIdResult>)(result.ReturnValue));
		}
	}
	
	public partial class dsd_mnt_S_TipoPagoResult
	{
		
		private int _N_IdTipoPago;
		
		private string _C_Descripcion;
		
		private bool _B_Estado;
		
		public dsd_mnt_S_TipoPagoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N_IdTipoPago", DbType="Int NOT NULL")]
		public int N_IdTipoPago
		{
			get
			{
				return this._N_IdTipoPago;
			}
			set
			{
				if ((this._N_IdTipoPago != value))
				{
					this._N_IdTipoPago = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Descripcion", DbType="VarChar(45)")]
		public string C_Descripcion
		{
			get
			{
				return this._C_Descripcion;
			}
			set
			{
				if ((this._C_Descripcion != value))
				{
					this._C_Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B_Estado", DbType="Bit NOT NULL")]
		public bool B_Estado
		{
			get
			{
				return this._B_Estado;
			}
			set
			{
				if ((this._B_Estado != value))
				{
					this._B_Estado = value;
				}
			}
		}
	}
	
	public partial class dsd_mnt_S_TipoPagoIdResult
	{
		
		private int _N_IdTipoPago;
		
		private string _C_Descripcion;
		
		private bool _B_Estado;
		
		public dsd_mnt_S_TipoPagoIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N_IdTipoPago", DbType="Int NOT NULL")]
		public int N_IdTipoPago
		{
			get
			{
				return this._N_IdTipoPago;
			}
			set
			{
				if ((this._N_IdTipoPago != value))
				{
					this._N_IdTipoPago = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Descripcion", DbType="VarChar(45)")]
		public string C_Descripcion
		{
			get
			{
				return this._C_Descripcion;
			}
			set
			{
				if ((this._C_Descripcion != value))
				{
					this._C_Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B_Estado", DbType="Bit NOT NULL")]
		public bool B_Estado
		{
			get
			{
				return this._B_Estado;
			}
			set
			{
				if ((this._B_Estado != value))
				{
					this._B_Estado = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
