//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Architecs.Test.ResidenteProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ResidenteProxy.IResidenteService")]
    public interface IResidenteService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResidenteService/ListarResidentes", ReplyAction="http://tempuri.org/IResidenteService/ListarResidentesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Architects.Dominio.ValidationException), Action="http://tempuri.org/IResidenteService/ListarResidentesValidationExceptionFault", Name="ValidationException", Namespace="http://schemas.datacontract.org/2004/07/Architects.Dominio")]
        Architects.Dominio.ResidenteBE[] ListarResidentes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResidenteService/BuscarResidentes", ReplyAction="http://tempuri.org/IResidenteService/BuscarResidentesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Architects.Dominio.ValidationException), Action="http://tempuri.org/IResidenteService/BuscarResidentesValidationExceptionFault", Name="ValidationException", Namespace="http://schemas.datacontract.org/2004/07/Architects.Dominio")]
        Architects.Dominio.ResidenteBE[] BuscarResidentes(string nombre, string apellidos, string numDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResidenteService/ListarResidentesPaginado", ReplyAction="http://tempuri.org/IResidenteService/ListarResidentesPaginadoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Architects.Dominio.ValidationException), Action="http://tempuri.org/IResidenteService/ListarResidentesPaginadoValidationExceptionF" +
            "ault", Name="ValidationException", Namespace="http://schemas.datacontract.org/2004/07/Architects.Dominio")]
        Architects.Dominio.ResidenteBE[] ListarResidentesPaginado(int page, int size);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResidenteService/ObtenerResidentePorID", ReplyAction="http://tempuri.org/IResidenteService/ObtenerResidentePorIDResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Architects.Dominio.ValidationException), Action="http://tempuri.org/IResidenteService/ObtenerResidentePorIDValidationExceptionFaul" +
            "t", Name="ValidationException", Namespace="http://schemas.datacontract.org/2004/07/Architects.Dominio")]
        Architects.Dominio.ResidenteBE ObtenerResidentePorID(int residente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResidenteService/ObtenerResidentePorNroDocumento", ReplyAction="http://tempuri.org/IResidenteService/ObtenerResidentePorNroDocumentoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Architects.Dominio.ValidationException), Action="http://tempuri.org/IResidenteService/ObtenerResidentePorNroDocumentoValidationExc" +
            "eptionFault", Name="ValidationException", Namespace="http://schemas.datacontract.org/2004/07/Architects.Dominio")]
        Architects.Dominio.ResidenteBE ObtenerResidentePorNroDocumento(string numeroDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResidenteService/CrearResidente", ReplyAction="http://tempuri.org/IResidenteService/CrearResidenteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Architects.Dominio.ValidationException), Action="http://tempuri.org/IResidenteService/CrearResidenteValidationExceptionFault", Name="ValidationException", Namespace="http://schemas.datacontract.org/2004/07/Architects.Dominio")]
        int CrearResidente(Architects.Dominio.ResidenteBE prmResidente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResidenteService/ActualizarResidente", ReplyAction="http://tempuri.org/IResidenteService/ActualizarResidenteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Architects.Dominio.ValidationException), Action="http://tempuri.org/IResidenteService/ActualizarResidenteValidationExceptionFault", Name="ValidationException", Namespace="http://schemas.datacontract.org/2004/07/Architects.Dominio")]
        Architects.Dominio.ValidationException ActualizarResidente(Architects.Dominio.ResidenteBE prmResidente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResidenteService/EliminarResidente", ReplyAction="http://tempuri.org/IResidenteService/EliminarResidenteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Architects.Dominio.ValidationException), Action="http://tempuri.org/IResidenteService/EliminarResidenteValidationExceptionFault", Name="ValidationException", Namespace="http://schemas.datacontract.org/2004/07/Architects.Dominio")]
        Architects.Dominio.ValidationException EliminarResidente(int residenteID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IResidenteServiceChannel : Architecs.Test.ResidenteProxy.IResidenteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ResidenteServiceClient : System.ServiceModel.ClientBase<Architecs.Test.ResidenteProxy.IResidenteService>, Architecs.Test.ResidenteProxy.IResidenteService {
        
        public ResidenteServiceClient() {
        }
        
        public ResidenteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ResidenteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResidenteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResidenteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Architects.Dominio.ResidenteBE[] ListarResidentes() {
            return base.Channel.ListarResidentes();
        }
        
        public Architects.Dominio.ResidenteBE[] BuscarResidentes(string nombre, string apellidos, string numDocumento) {
            return base.Channel.BuscarResidentes(nombre, apellidos, numDocumento);
        }
        
        public Architects.Dominio.ResidenteBE[] ListarResidentesPaginado(int page, int size) {
            return base.Channel.ListarResidentesPaginado(page, size);
        }
        
        public Architects.Dominio.ResidenteBE ObtenerResidentePorID(int residente) {
            return base.Channel.ObtenerResidentePorID(residente);
        }
        
        public Architects.Dominio.ResidenteBE ObtenerResidentePorNroDocumento(string numeroDocumento) {
            return base.Channel.ObtenerResidentePorNroDocumento(numeroDocumento);
        }
        
        public int CrearResidente(Architects.Dominio.ResidenteBE prmResidente) {
            return base.Channel.CrearResidente(prmResidente);
        }
        
        public Architects.Dominio.ValidationException ActualizarResidente(Architects.Dominio.ResidenteBE prmResidente) {
            return base.Channel.ActualizarResidente(prmResidente);
        }
        
        public Architects.Dominio.ValidationException EliminarResidente(int residenteID) {
            return base.Channel.EliminarResidente(residenteID);
        }
    }
}
