#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Architecs.ViviendasService.Persistencia
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CondominiosDB")]
	public partial class DBML_ViviendaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DBML_ViviendaDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["cnxCondominiosDB"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBML_ViviendaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBML_ViviendaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBML_ViviendaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBML_ViviendaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Maestros.dsd_mnt_I_Vivienda")]
		public int dsd_mnt_I_Vivienda([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> prm_N_IdVivienda, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_N_IdResidente, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string prm_C_NumEdificio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string prm_C_NumDpto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,0)")] System.Nullable<decimal> prm_N_NumMetros, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string prm_C_CodTipo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), prm_N_IdVivienda, prm_N_IdResidente, prm_C_NumEdificio, prm_C_NumDpto, prm_N_NumMetros, prm_C_CodTipo);
			prm_N_IdVivienda = ((System.Nullable<int>)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Maestros.dsd_mnt_D_Vivienda")]
		public int dsd_mnt_D_Vivienda([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_N_IdVivienda)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), prm_N_IdVivienda);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Maestros.dsd_mnt_S_ViviendaId")]
		public ISingleResult<dsd_mnt_S_ViviendaIdResult> dsd_mnt_S_ViviendaId([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_N_IdVivienda)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), prm_N_IdVivienda);
			return ((ISingleResult<dsd_mnt_S_ViviendaIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Maestros.dsd_mnt_U_Vivienda")]
		public int dsd_mnt_U_Vivienda([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_N_IdVivienda, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_N_IdResidente, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string prm_C_NumEdificio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string prm_C_NumDpto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,0)")] System.Nullable<decimal> prm_N_NumMetros, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string prm_C_CodTipo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> prm_B_Estado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), prm_N_IdVivienda, prm_N_IdResidente, prm_C_NumEdificio, prm_C_NumDpto, prm_N_NumMetros, prm_C_CodTipo, prm_B_Estado);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Maestros.dsd_mnt_S_Vivienda")]
		public ISingleResult<dsd_mnt_S_ViviendaResult> dsd_mnt_S_Vivienda([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_N_IdResidente, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string prm_C_NumEdificio)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), prm_N_IdResidente, prm_C_NumEdificio);
			return ((ISingleResult<dsd_mnt_S_ViviendaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Maestros.dsd_mnt_S_ViviendaDpto")]
		public ISingleResult<dsd_mnt_S_ViviendaDptoResult> dsd_mnt_S_ViviendaDpto([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string prm_C_NumDpto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string prm_C_NumEdificio)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), prm_C_NumDpto, prm_C_NumEdificio);
			return ((ISingleResult<dsd_mnt_S_ViviendaDptoResult>)(result.ReturnValue));
		}
	}
	
	public partial class dsd_mnt_S_ViviendaIdResult
	{
		
		private int _N_IdVivienda;
		
		private int _N_IdResidente;
		
		private string _C_NumEdificio;
		
		private string _C_NumDpto;
		
		private System.Nullable<decimal> _N_NumMetros;
		
		private string _C_CodTipo;
		
		private bool _B_Estado;
		
		public dsd_mnt_S_ViviendaIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N_IdVivienda", DbType="Int NOT NULL")]
		public int N_IdVivienda
		{
			get
			{
				return this._N_IdVivienda;
			}
			set
			{
				if ((this._N_IdVivienda != value))
				{
					this._N_IdVivienda = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N_IdResidente", DbType="Int NOT NULL")]
		public int N_IdResidente
		{
			get
			{
				return this._N_IdResidente;
			}
			set
			{
				if ((this._N_IdResidente != value))
				{
					this._N_IdResidente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_NumEdificio", DbType="VarChar(10)")]
		public string C_NumEdificio
		{
			get
			{
				return this._C_NumEdificio;
			}
			set
			{
				if ((this._C_NumEdificio != value))
				{
					this._C_NumEdificio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_NumDpto", DbType="VarChar(10)")]
		public string C_NumDpto
		{
			get
			{
				return this._C_NumDpto;
			}
			set
			{
				if ((this._C_NumDpto != value))
				{
					this._C_NumDpto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N_NumMetros", DbType="Decimal(12,2)")]
		public System.Nullable<decimal> N_NumMetros
		{
			get
			{
				return this._N_NumMetros;
			}
			set
			{
				if ((this._N_NumMetros != value))
				{
					this._N_NumMetros = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_CodTipo", DbType="VarChar(5)")]
		public string C_CodTipo
		{
			get
			{
				return this._C_CodTipo;
			}
			set
			{
				if ((this._C_CodTipo != value))
				{
					this._C_CodTipo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B_Estado", DbType="Bit NOT NULL")]
		public bool B_Estado
		{
			get
			{
				return this._B_Estado;
			}
			set
			{
				if ((this._B_Estado != value))
				{
					this._B_Estado = value;
				}
			}
		}
	}
	
	public partial class dsd_mnt_S_ViviendaResult
	{
		
		private int _N_IdVivienda;
		
		private int _N_IdResidente;
		
		private string _Column1;
		
		private string _C_NumEdificio;
		
		private string _C_NumDpto;
		
		private System.Nullable<decimal> _N_NumMetros;
		
		private string _C_CodTipo;
		
		private bool _B_Estado;
		
		public dsd_mnt_S_ViviendaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N_IdVivienda", DbType="Int NOT NULL")]
		public int N_IdVivienda
		{
			get
			{
				return this._N_IdVivienda;
			}
			set
			{
				if ((this._N_IdVivienda != value))
				{
					this._N_IdVivienda = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N_IdResidente", DbType="Int NOT NULL")]
		public int N_IdResidente
		{
			get
			{
				return this._N_IdResidente;
			}
			set
			{
				if ((this._N_IdResidente != value))
				{
					this._N_IdResidente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="VarChar(182)")]
		public string Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_NumEdificio", DbType="VarChar(10)")]
		public string C_NumEdificio
		{
			get
			{
				return this._C_NumEdificio;
			}
			set
			{
				if ((this._C_NumEdificio != value))
				{
					this._C_NumEdificio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_NumDpto", DbType="VarChar(10)")]
		public string C_NumDpto
		{
			get
			{
				return this._C_NumDpto;
			}
			set
			{
				if ((this._C_NumDpto != value))
				{
					this._C_NumDpto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N_NumMetros", DbType="Decimal(12,2)")]
		public System.Nullable<decimal> N_NumMetros
		{
			get
			{
				return this._N_NumMetros;
			}
			set
			{
				if ((this._N_NumMetros != value))
				{
					this._N_NumMetros = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_CodTipo", DbType="VarChar(5)")]
		public string C_CodTipo
		{
			get
			{
				return this._C_CodTipo;
			}
			set
			{
				if ((this._C_CodTipo != value))
				{
					this._C_CodTipo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B_Estado", DbType="Bit NOT NULL")]
		public bool B_Estado
		{
			get
			{
				return this._B_Estado;
			}
			set
			{
				if ((this._B_Estado != value))
				{
					this._B_Estado = value;
				}
			}
		}
	}
	
	public partial class dsd_mnt_S_ViviendaDptoResult
	{
		
		private int _N_IdVivienda;
		
		private int _N_IdResidente;
		
		private string _C_NumEdificio;
		
		private string _C_NumDpto;
		
		private System.Nullable<decimal> _N_NumMetros;
		
		private string _C_CodTipo;
		
		private bool _B_Estado;
		
		public dsd_mnt_S_ViviendaDptoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N_IdVivienda", DbType="Int NOT NULL")]
		public int N_IdVivienda
		{
			get
			{
				return this._N_IdVivienda;
			}
			set
			{
				if ((this._N_IdVivienda != value))
				{
					this._N_IdVivienda = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N_IdResidente", DbType="Int NOT NULL")]
		public int N_IdResidente
		{
			get
			{
				return this._N_IdResidente;
			}
			set
			{
				if ((this._N_IdResidente != value))
				{
					this._N_IdResidente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_NumEdificio", DbType="VarChar(10)")]
		public string C_NumEdificio
		{
			get
			{
				return this._C_NumEdificio;
			}
			set
			{
				if ((this._C_NumEdificio != value))
				{
					this._C_NumEdificio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_NumDpto", DbType="VarChar(10)")]
		public string C_NumDpto
		{
			get
			{
				return this._C_NumDpto;
			}
			set
			{
				if ((this._C_NumDpto != value))
				{
					this._C_NumDpto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N_NumMetros", DbType="Decimal(12,2)")]
		public System.Nullable<decimal> N_NumMetros
		{
			get
			{
				return this._N_NumMetros;
			}
			set
			{
				if ((this._N_NumMetros != value))
				{
					this._N_NumMetros = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_CodTipo", DbType="VarChar(5)")]
		public string C_CodTipo
		{
			get
			{
				return this._C_CodTipo;
			}
			set
			{
				if ((this._C_CodTipo != value))
				{
					this._C_CodTipo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B_Estado", DbType="Bit NOT NULL")]
		public bool B_Estado
		{
			get
			{
				return this._B_Estado;
			}
			set
			{
				if ((this._B_Estado != value))
				{
					this._B_Estado = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
