//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.SOAPagosService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SOAPagosService.ICuotaService")]
    public interface ICuotaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuotaService/ListarTipoPago", ReplyAction="http://tempuri.org/ICuotaService/ListarTipoPagoResponse")]
        Architects.Dominio.TipoPago[] ListarTipoPago();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuotaService/CrearTipoPago", ReplyAction="http://tempuri.org/ICuotaService/CrearTipoPagoResponse")]
        Architects.Dominio.TipoPago CrearTipoPago(string Descripcion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICuotaServiceChannel : Test.SOAPagosService.ICuotaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CuotaServiceClient : System.ServiceModel.ClientBase<Test.SOAPagosService.ICuotaService>, Test.SOAPagosService.ICuotaService {
        
        public CuotaServiceClient() {
        }
        
        public CuotaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CuotaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CuotaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CuotaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Architects.Dominio.TipoPago[] ListarTipoPago() {
            return base.Channel.ListarTipoPago();
        }
        
        public Architects.Dominio.TipoPago CrearTipoPago(string Descripcion) {
            return base.Channel.CrearTipoPago(Descripcion);
        }
    }
}
