//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.SOAResidenteService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SOAResidenteService.IResidenteService")]
    public interface IResidenteService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResidenteService/CrearResidente", ReplyAction="http://tempuri.org/IResidenteService/CrearResidenteResponse")]
        int CrearResidente(int n_IdResidente, string c_Nombre, string c_Apellidos, int n_TipoDoc, string c_NumDocume, System.DateTime D_FecNacimi, string c_Correo, string c_Clave, bool b_Estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResidenteService/ListarResidente", ReplyAction="http://tempuri.org/IResidenteService/ListarResidenteResponse")]
        Architects.Dominio.Residente[] ListarResidente();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IResidenteServiceChannel : Test.SOAResidenteService.IResidenteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ResidenteServiceClient : System.ServiceModel.ClientBase<Test.SOAResidenteService.IResidenteService>, Test.SOAResidenteService.IResidenteService {
        
        public ResidenteServiceClient() {
        }
        
        public ResidenteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ResidenteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResidenteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResidenteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CrearResidente(int n_IdResidente, string c_Nombre, string c_Apellidos, int n_TipoDoc, string c_NumDocume, System.DateTime D_FecNacimi, string c_Correo, string c_Clave, bool b_Estado) {
            return base.Channel.CrearResidente(n_IdResidente, c_Nombre, c_Apellidos, n_TipoDoc, c_NumDocume, D_FecNacimi, c_Correo, c_Clave, b_Estado);
        }
        
        public Architects.Dominio.Residente[] ListarResidente() {
            return base.Channel.ListarResidente();
        }
    }
}
