#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Architecs.HorariosService.Persitencia
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CondominiosDB")]
	public partial class DBMLHorariosDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DBMLHorariosDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["CondominiosDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBMLHorariosDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBMLHorariosDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBMLHorariosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBMLHorariosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Gestion.omgc_mnt_GetAllFromHorario")]
		public ISingleResult<omgc_mnt_GetAllFromHorarioResult> omgc_mnt_GetAllFromHorario()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<omgc_mnt_GetAllFromHorarioResult>)(result.ReturnValue));
		}
	}
	
	public partial class omgc_mnt_GetAllFromHorarioResult
	{
		
		private int _N_IdHorario;
		
		private string _C_Rango;
		
		private int _B_Estado;
		
		public omgc_mnt_GetAllFromHorarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N_IdHorario", DbType="Int NOT NULL")]
		public int N_IdHorario
		{
			get
			{
				return this._N_IdHorario;
			}
			set
			{
				if ((this._N_IdHorario != value))
				{
					this._N_IdHorario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Rango", DbType="VarChar(45)")]
		public string C_Rango
		{
			get
			{
				return this._C_Rango;
			}
			set
			{
				if ((this._C_Rango != value))
				{
					this._C_Rango = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B_Estado", DbType="Int NOT NULL")]
		public int B_Estado
		{
			get
			{
				return this._B_Estado;
			}
			set
			{
				if ((this._B_Estado != value))
				{
					this._B_Estado = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
