//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Architecs.Presentacion.HorarioService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HorarioBE", Namespace="http://schemas.datacontract.org/2004/07/Architects.Dominio")]
    [System.SerializableAttribute()]
    public partial class HorarioBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int B_EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C_RangoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int N_IdHorarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int B_Estado {
            get {
                return this.B_EstadoField;
            }
            set {
                if ((this.B_EstadoField.Equals(value) != true)) {
                    this.B_EstadoField = value;
                    this.RaisePropertyChanged("B_Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string C_Rango {
            get {
                return this.C_RangoField;
            }
            set {
                if ((object.ReferenceEquals(this.C_RangoField, value) != true)) {
                    this.C_RangoField = value;
                    this.RaisePropertyChanged("C_Rango");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int N_IdHorario {
            get {
                return this.N_IdHorarioField;
            }
            set {
                if ((this.N_IdHorarioField.Equals(value) != true)) {
                    this.N_IdHorarioField = value;
                    this.RaisePropertyChanged("N_IdHorario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HorarioService.IHorarioService")]
    public interface IHorarioService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHorarioService/ListarHorariosDisponibles", ReplyAction="http://tempuri.org/IHorarioService/ListarHorariosDisponiblesResponse")]
        System.Collections.Generic.List<Architecs.Presentacion.HorarioService.HorarioBE> ListarHorariosDisponibles(System.DateTime fecha, int idEspacio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHorarioService/RegistrarHorario", ReplyAction="http://tempuri.org/IHorarioService/RegistrarHorarioResponse")]
        Architecs.Presentacion.HorarioService.HorarioBE RegistrarHorario(string rango);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHorarioService/ActualizarHorario", ReplyAction="http://tempuri.org/IHorarioService/ActualizarHorarioResponse")]
        Architecs.Presentacion.HorarioService.HorarioBE ActualizarHorario(int idHorario, string rango, int estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHorarioService/EliminarHorario", ReplyAction="http://tempuri.org/IHorarioService/EliminarHorarioResponse")]
        void EliminarHorario(int idHorario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHorarioServiceChannel : Architecs.Presentacion.HorarioService.IHorarioService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HorarioServiceClient : System.ServiceModel.ClientBase<Architecs.Presentacion.HorarioService.IHorarioService>, Architecs.Presentacion.HorarioService.IHorarioService {
        
        public HorarioServiceClient() {
        }
        
        public HorarioServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HorarioServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HorarioServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HorarioServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Architecs.Presentacion.HorarioService.HorarioBE> ListarHorariosDisponibles(System.DateTime fecha, int idEspacio) {
            return base.Channel.ListarHorariosDisponibles(fecha, idEspacio);
        }
        
        public Architecs.Presentacion.HorarioService.HorarioBE RegistrarHorario(string rango) {
            return base.Channel.RegistrarHorario(rango);
        }
        
        public Architecs.Presentacion.HorarioService.HorarioBE ActualizarHorario(int idHorario, string rango, int estado) {
            return base.Channel.ActualizarHorario(idHorario, rango, estado);
        }
        
        public void EliminarHorario(int idHorario) {
            base.Channel.EliminarHorario(idHorario);
        }
    }
}
